### ISSUE TITLE
Make getting a PCE App easy

### ISSUE THREAD

**Issue by milstan** [blindnet-io/privacy-computation-engine#23]
## Context
 Currently, when you want to build your privacy portal using blindnet devkit, you are supposed to make a webpage, include the PRCI web component and give to it a URL of the PCE. See example here:
```
<!DOCTYPE html>
<html lang="en-GB">
  <head>
    <meta charset="utf-8" />
    <title>Privacy Components for the Web - Minimal Static Demo</title>
  </head>
  <body>
    <h1>Privacy Components for the Web - Minimal Static Demo</h1>

    <h2>Assert Your Privacy Rights</h2>

    <bldn-priv-request computation-base-url="http://localhost:9000/v0"></bldn-priv-request>

    <script src="https://unpkg.com/@blindnet/prci/dist/index.core.min.js?module" type="module"></script>
  </body>
</html>
```

## Intended outcome

I want to make the integration, for clients using our PCE instance, as quick as possible. So I want them to get (from us, or maybe later through an interface) a URL* to provide in the computation-base-url argument, so that they can really have an easy quick-start.

It should also be possible (independently of this web page and the example code given above) to provide configuration meta-data/settings to configure the PCE App.

*several clients get to use the same URL, but must specify particular app id and other ifnromation used to identify them.

**Comment by m4rk055** [comment]
If no url is provided, staging one is used.


> It should also be possible (independently of this web page and the example code given above) to provide configuration meta-data/settings to configure the PCE App.

PCE configuration settings shouldn't be set here since it's a data subject facing component. Do you have some particular setting in mind?

> *several clients get to use the same URL, but must specify particular app id and other ifnromation used to identify them.

App information is extracted from the token, so no need to specify it in this component.

**Comment by milstan** [comment]
I am fine with all you wrote. My issue description is slightly outdated.
