### ISSUE TITLE
Refactor names of parameters of Demand Resolution Strategy

### ISSUE THREAD

**Issue by milstan** [blindnet-io/privacy-computation-engine#29]
Currently the Demand Resolution Strategy schema of the PCE API uses a different vocabulary than the rest of the components. 

For consistency, I suggest:
- renaming those parameters to clearly mirror the exact PRIV terms associated with Demand Actions (e.g. instead of `consents` call it `revoke-consent`
- allowing to set automatic/non automatic processing for OBJECT and RESTRICT

Also the documentation is rather limited, i.e. we must say what are other allowed values - how to set non-automatic processing of certain requests. Places this change should affect:
- [ ] [swagger](https://stage.computing.blindnet.io/swagger/#/Configuration/putV0ConfigureDemand-resolution-strategy)
- [ ] [blindnet.dev](https://github.com/blindnet-io/blindnet.dev/blob/main/docs/03-computation/02-configuration.mdx)

**Comment by m4rk055** [comment]
`consents` is a catch-all category for all `revoke-consent`, `object` and `restrict`. Should we have settings for all 3 separately?

**Comment by milstan** [comment]
I think it is more intutitive to have 1:1 between ACTION values and this schema here. The users of our system MUST learn about types of demands (i.e. ACTIONs) so we can safely assume they know them. the catch-all term `consents` introduce an additional concept to learn, which we want to reduce to the minimum.
