### ISSUE TITLE
Improve handling of regulations

### ISSUE THREAD

**Issue by milstan** [blindnet-io/privacy-computation-engine#30]
Curently, adding a regulation is possible by providing a regulation ID. It is not clear which ID whould one provide to add the pre-defined GDPR regulation.

I suggest to:
- change the add a method for creating rule-sets, inspired by the format given in the pre-defnied [GDPR rule-set](https://stage.computing.blindnet.io/swagger/#/Configuration/putV0ConfigureRegulations).
- better document the PUT regulations method to take this into account, in both [swagger](https://stage.computing.blindnet.io/swagger/#/Configuration/putV0ConfigureRegulations) and [blindnet.dev](https://github.com/blindnet-io/blindnet.dev/blob/main/docs/03-computation/02-configuration.mdx)

**Comment by m4rk055** [comment]
The idea is to [obtain a list of regulations with their ids](https://stage.computing.blindnet.io/swagger/#/Configuration/getV0ConfigureRegulations), and then choose which [ids to add](https://stage.computing.blindnet.io/swagger/#/Configuration/putV0ConfigureRegulations).

**Comment by milstan** [comment]
True, I forgot that this is the design we chose. Then just update the documentation for now, so that this is clear, and make sure the description of the GDPR regulation links to the github page where all the rules from it are listed.
